# Aplicação WEB
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webpeso
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webpeso
  template:
    metadata:
      labels:
        app: webpeso
    spec:
      containers:
        - name: webpeso
          image: desenvolvimentovitoria/conversao-peso:v1
          ports:
            - containerPort: 80
---
# Service da aplicação WEB
apiVersion: v1
kind: Service
metadata:
  name: webpeso
spec:
  selector:
    app: webpeso
  ports: 
    - port: 80
      targetPort: 80
      nodePort: 30000
  type: NodePort
  